### ISSUE TITLE
Can we have any example or demo?

### ISSUE THREAD

**Issue by DhruvAerosol** [tonickkozlov/vue-tweet-embed#1]
**Help Wanted**
Can we have any **example** or **demo**?
i am not getting how to use it in vuejs webpack template.

**Comment by tonickkozlov** [comment]
What confuses you, exactly? To my understanding, you'd have to
'''
npm install vue-tweet-embed
'''
In the root of your project, and then use it the same way as you would any other vue component (see readme). Let me know if you run into issues!

**Comment by DhruvAerosol** [comment]
Unknown custom element: <tweet> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

## main.js ##
```
import Vue from 'vue'
import App from './App.vue'
import Tweet from 'vue-tweet-embed'


new Vue({
  el: 'body',
  components: { App }
})
```

---
## App.vue ##

```
<template>
  <div id="app">
    <h1>{{ title }}</h1>
    <hr>
  </div>
  <Tweet :id="'692527862369357824'"></Tweet>
</template>

<script>
import TodoList from './todo-list.vue'
import Tweet from 'vue-tweet-embed'

export default {
  data () {
    return {
      newItem: '',
      title: 'Todo List'
    }
  },

  methods: {
  }
}
</script>
```

**Comment by tonickkozlov** [comment]
Please refer to https://vuejs.org/v2/guide/components.html#Local-Registration
basically, you are missing 'components' property for the component to operate correctly.

**Comment by VigneshVaidyanathan** [comment]
Hello,
I am very new to Vue and I am facing this issue. I have also added the local registration in the component I am trying to use. Is there anything I am missing? I am using the component inside a custom component so I didnt have to do the global registration.

```
<script>
import wallets from "../../components/wallets.vue";
import registerComponent from "../../components/auth/register.vue";
import airdrop from "../../components/airdrop/airdrop.vue";
import Tweet from "vue-tweet-embed";

export default {
  components: {
    "tweet-embed": Tweet,
    wallets,
    "my-airdrop": airdrop,
    registerComponent,
  },
  props: ["model", "userModel", "antiForgeryToken", "siteKey"],
  data: () => {
    return {
      airdrops: null
    };
  },
};
</script>

<template>
<tweet-embed :id="'692527862369357824'"></tweet-embed>
</template>
```
