### ISSUE TITLE
How it handles tweet, if it has been deleted?

### ISSUE THREAD

**Issue by DhruvAerosol** [tonickkozlov/vue-tweet-embed#2]
As it can display loader, how to display any message or image if tweet is deleted or not available?

**Comment by antkozlo** [comment]
There's no such functionality in place yet since the library is just a wrapper over Twitter's API lib which does not support this. I'll take a look at this problem if I have a chance. If you have a solution in mind, please create a PR to this repo.

**Comment by tonickkozlov** [comment]
There's no such functionality in place yet since the library is just a wrapper over Twitter's API lib which does not support this. I'll take a look at this problem if I have a chance. If you have a solution in mind, please create a PR to this repo.

**Comment by DhruvAerosol** [comment]
i am not able to run the code.
i want to create PR of my changes.
but it shows "Permission to tonickkozlov/vue-tweet-embed.git denied to DhruvAerosol."
what should i do now?.

**Comment by tonickkozlov** [comment]
You'd have to fork this repo, commit your changes and push them to your forked remote, and create a PR from there to this repo.

**Comment by DhruvAerosol** [comment]
What should i add in tests?
i have prepared tests same like given, just changed id '123' to '14' and DOM id 'foo1 => 'bar1'. i have run test and it shows: '9 tests passed'. so is it ok?'
if it's not proper then can you add it i have mentioned in my forked code's ReadME file.
Or guide me how can i add it.

[append_tests.txt](https://github.com/tonickkozlov/vue-tweet-embed/files/1241912/append_tests.txt)

**Comment by tonickkozlov** [comment]
Your PR has been merged, see v1.2.1
