### ISSUE TITLE
Concat var value in 'error-message' string

### ISSUE THREAD

**Issue by DhruvAerosol** [tonickkozlov/vue-tweet-embed#25]
the error-message does not concat var value with it.
can any one guide.
i tried this:
`<tweet error-message="'Sorry the tweet'+tweet_id+'is not available'"></tweet>`

**Comment by aevaldas** [comment]
You have to add `:` before the param name to use concated string as variable: `<tweet :error-message="'Sorry the tweet'+tweet_id+'is not available'"></tweet>`

**Comment by DhruvAerosol** [comment]
yeah it worked,@aevaldas thanks.
and what if i also want to hyperlink some text in it like link or else?
example: 
`<tweet :error-message="'Sorry the tweet <a>https://twitter.com/user/'+tweet_id+ '</a> is not available'"></tweet>`

**Comment by aevaldas** [comment]
Right hyperlink in this tag should look like this:
<tweet :error-message="'Sorry the <a href=\'https://twitter.com/user/'+tweet_id+ '\'>tweet</a> is not available'"></tweet>

Currently html in error-message is not supported.
Created a merge request to solve this issue: https://github.com/tonickkozlov/vue-tweet-embed/pull/26

**Comment by tonickkozlov** [comment]
Closed in v2.4.0
#40
